services:
  - type: web
    name: rover-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        generateValue: true
